import type { Metadata } from "next";
import { Crimson_Text, Roboto } from "next/font/google";
import Header from "@professor-blog/components/Header";
import "./globals.css";
import Footer from "@professor-blog/components/Footer";

const font = Roboto({
  weight: "500",
  style: "normal",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Professor Dr S Jayarama Reddy M.Sc., Ph.D.",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-[#EEF5FF] ${font.className}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
